
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author galifu
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        Dimension screenSize= Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setUndecorated(true);
        this.setVisible(true);
        initComponents();
       //new bloquear( this ).block();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbentradaprin = new javax.swing.JButton();
        jcprincipal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFocusableWindowState(false);
        setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbentradaprin.setBackground(new java.awt.Color(0, 0, 0));
        jbentradaprin.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jbentradaprin.setForeground(new java.awt.Color(255, 255, 255));
        jbentradaprin.setText("OK");
        jbentradaprin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbentradaprinActionPerformed(evt);
            }
        });
        jPanel1.add(jbentradaprin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, -1, 20));

        jcprincipal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Docente", "PAAE", "Egresado" }));
        jcprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcprincipalActionPerformed(evt);
            }
        });
        jPanel1.add(jcprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 90, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu Mono", 0, 24)); // NOI18N
        jLabel4.setText("Seleccione una opción");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esime.png"))); // NOI18N
        jLabel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel2PropertyChange(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel5.setBackground(new java.awt.Color(69, 174, 79,220));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 360, 370));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo.jpg"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize() );
        jLabel3.setMinimumSize(Toolkit.getDefaultToolkit().getScreenSize() );
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1383, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Jfprin");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbentradaprinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbentradaprinActionPerformed
String prin = (String)jcprincipal.getSelectedItem(); 
       // if(prin.equals("Alumno")) 
         //   new Alumnos().setVisible(true);
        if( prin.equals("Docente")){
            new Docente().setVisible(true);
            this.dispose();
        }
       // if(prin.equals("PAAE")) 
         //   new PAAE().setVisible(true);
       // if( prin.equals("Egresado"))
         //   new Egresado().setVisible(true);
        
    }//GEN-LAST:event_jbentradaprinActionPerformed
    
    
    private void jcprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcprincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcprincipalActionPerformed

    private void jLabel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2PropertyChange

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
               new Principal();
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbentradaprin;
    private javax.swing.JComboBox<String> jcprincipal;
    // End of variables declaration//GEN-END:variables
}
