
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

/**
 *
 * @author galifu
 */
public class Sesion extends java.awt.Frame {

    /**
     * Creates new form Sesion
     */
    public Sesion() {
        
        Dimension screenSize= Toolkit.getDefaultToolkit().getScreenSize();
        this.setUndecorated(true);
        this.setLocation(0, screenSize.height/3);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbcerrarsesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255,200));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbcerrarsesion.setBackground(new java.awt.Color(204, 204, 204));
        jbcerrarsesion.setText("<html>\n<center>\nC<br>\ne<br>\nr<br>\nr<br>\na<br>\nr <br>\n<br>\nS<br>\ne<br>\ns<br>\ni<br>\nó<br>\nn<br>\n</center>\n</html>");
        jbcerrarsesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbcerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcerrarsesionActionPerformed(evt);
            }
        });
        add(jbcerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 20, 230));
        jbcerrarsesion.getAccessibleContext().setAccessibleName("");

        jLabel2.setText("Aquí va la boleta");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jbcerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcerrarsesionActionPerformed
        new Principal().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jbcerrarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sesion().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbcerrarsesion;
    // End of variables declaration//GEN-END:variables
}
