package prueba;


import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import org.json.JSONObject;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONArray;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author galifu
 */
public class Docente extends javax.swing.JFrame {
private int valor;
    /**
     * Creates new form Alumnos
     */
    public Docente(int valor) {
        
        this.setExtendedState(MAXIMIZED_BOTH);//lo de pricipal x2
        this.setUndecorated(true);
         this.valor=valor;
        initComponents();
        new bloquear( this ).block();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public String usuario(){
       
        String usu = jftnumero.getText();
        return usu;
   }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlwel = new javax.swing.JLabel();
        jftnumero = new javax.swing.JTextField();
        jbiniciarsesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbregistro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jptpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlwel.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jlwel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlwel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jlwel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 280, 40));

        jftnumero.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        jftnumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftnumeroActionPerformed(evt);
            }
        });
        jPanel1.add(jftnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 280, -1));

        jbiniciarsesion.setBackground(new java.awt.Color(0, 0, 0));
        jbiniciarsesion.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jbiniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        jbiniciarsesion.setText("Iniciar Sesión");
        jbiniciarsesion.setBorder(null);
        jbiniciarsesion.setBorderPainted(false);
        jbiniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbiniciarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(jbiniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        jLabel2.setText("¿Todavía no tienes cuenta? ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, 20));

        jbregistro.setForeground(new java.awt.Color(51, 51, 255));
        jbregistro.setText("Registrate");
        jbregistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbregistro.setBorderPainted(false);
        jbregistro.setContentAreaFilled(false);
        jbregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbregistroActionPerformed(evt);
            }
        });
        jPanel1.add(jbregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255, 1));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        jptpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jptpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 280, -1));

        jLabel4.setBackground(new java.awt.Color(69, 174, 79, 220));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 360, 280));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabel3.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jftnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftnumeroActionPerformed
        
    }//GEN-LAST:event_jftnumeroActionPerformed

    private void jbiniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbiniciarsesionActionPerformed
       
        if(valor==4){
            String password=  jptpass.getText();
            if(password.equals("1sl@2023")){
                new Configuracion().setVisible(true);
                this.dispose();
            }else{
                new Principal().setVisible(true);
                this.dispose();
            }
        }else{
        String url = "http://148.204.37.66/serverRegistroLabs/login.php";
        String charset = "UTF-8";
        String idAcceso;
        // Datos a enviar en la solicitud POST
        String idUsuario = jftnumero.getText();
         //obtencion de lo que esta dentro del archivo Computadora
        String filePath = "Computadora.txt";
        StringBuilder contenidoArchivo = new StringBuilder();
        try {
            FileReader fileReader = new FileReader(filePath);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            String linea;
            while ((linea = bufferedReader.readLine()) != null) {
                contenidoArchivo.append(linea);
            }
            bufferedReader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        String idComputadora = contenidoArchivo.toString();
        //hasta aqui 
        
        try {
            // Codificar los parámetros
            String parametros = "idUsuario=" + URLEncoder.encode(idUsuario, charset)
                    + "&idComputadora=" + URLEncoder.encode(idComputadora, charset);

            // Crear la conexión HTTP POST
            URL urlObj = new URL(url);
            HttpURLConnection conn = (HttpURLConnection) urlObj.openConnection();
            conn.setRequestMethod("POST");
            conn.setDoOutput(true);

            // Enviar los parámetros en el cuerpo de la solicitud
            try (DataOutputStream wr = new DataOutputStream(conn.getOutputStream())) {
                wr.writeBytes(parametros);
                wr.flush();
            }

            // Obtener la respuesta del servidor
            BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            String linea;
            StringBuilder respuesta = new StringBuilder();
            while ((linea = in.readLine()) != null) {
                respuesta.append(linea);
            }
            in.close();

            // Procesar la respuesta
            String jsonRespuesta = respuesta.toString();
            //System.out.println(jsonRespuesta);

            if(jsonRespuesta.contains("[{\"res\":-1}]")){
                JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Usuario no encontrado, Registrate o Intentalo de nuevo");
                
            }else{
                // Leer el contenido de la respuesta
                    JSONArray jsonArray = new JSONArray(jsonRespuesta);
                    JSONObject jsonObject = jsonArray.getJSONObject(0);

                    // Obtener el valor de "res"
                    int resValue = jsonObject.getInt("res");
                    //System.out.println("idAcceso es: " + resValue);

                    // Crear el archivo "idAcceso" y escribir la respuesta
                    FileWriter fileWriter = new FileWriter("idAcceso.txt");
                    fileWriter.write(String.valueOf(resValue));
                    fileWriter.close();
                    String url2 = "http://148.204.37.66/serverRegistroLabs/checkAccess.php";
                    String charset2 = "UTF-8";
                    String parametros2 = "idUsuario=" + URLEncoder.encode(idUsuario, charset2);

                    // Crear la conexión HTTP POST
                    URL urlObj2 = new URL(url2);
                    HttpURLConnection con = (HttpURLConnection) urlObj2.openConnection();
                    con.setRequestMethod("POST");
                    con.setDoOutput(true);

                    // Enviar los parámetros en el cuerpo de la solicitud
                    try (DataOutputStream wr2 = new DataOutputStream(con.getOutputStream())) {
                        wr2.writeBytes(parametros2);
                        wr2.flush();


                    // Obtener la respuesta del servidor
                        BufferedReader in2 = new BufferedReader(new InputStreamReader(con.getInputStream()));
                        String linea2;
                        StringBuilder respuesta2 = new StringBuilder();
                        while ((linea2 = in2.readLine()) != null) {
                            respuesta2.append(linea2);
                        }
                        in2.close();
                        
                        // Procesar la respuesta
                        String jsonRespuesta2 = respuesta2.toString();
                        //System.out.println(jsonRespuesta2);

                        if(jsonRespuesta2.contains("true")){
                            new Encuestaok_1().setVisible(true);
                            this.dispose();
                            
                        }else{
                            new Sesionok(usuario()).setVisible(true);
                            this.dispose();
                        }
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbiniciarsesionActionPerformed

    private void jbregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbregistroActionPerformed
       //este boton te manda a registrarte
       
       if(valor==0) {
           Registro reg =new Registro(valor);
           reg.jLnumeror.setText("Número de boleta");
           reg.jLcarrdepto.setText("Carrera");
           reg.jCdeptos.setVisible(false);
           reg.setVisible(true);
           this.dispose();
       }
       if(valor==1) {Registro reg =new Registro(valor);
           reg.jLnumeror.setText("Número de empleado");
           reg.jLcarrdepto.setText("Carrera");
           reg.jCdeptos.setVisible(false);
           reg.setVisible(true);
           this.dispose();
       }
       if(valor==3) {
           Registro reg =new Registro(valor);
           reg.jLnumeror.setText("Número de empleado");
           reg.jLcarrdepto.setText("Departamento");
           reg.jccarreras.setVisible(false);
           reg.setVisible(true);
           this.dispose();
       }
       if(valor==2) {
           Registro reg =new Registro(valor);
           reg.jLnumeror.setText("Número de boleta");
           reg.jLcarrdepto.setText("Carrera");
           reg.jCdeptos.setVisible(false);
           reg.setVisible(true);
           this.dispose();
       }
       
       
       
       
        
    }//GEN-LAST:event_jbregistroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //regresa a la principal
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Docente().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbiniciarsesion;
    public javax.swing.JButton jbregistro;
    public javax.swing.JTextField jftnumero;
    public javax.swing.JLabel jlwel;
    public javax.swing.JPasswordField jptpass;
    // End of variables declaration//GEN-END:variables
}
