package prueba;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
/**
 *
 * @author galifu
 */
public class Registro extends javax.swing.JFrame {
private int valor;
    /**
     * Creates new form Registro
     */
    public Registro(int valor) {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setUndecorated(true);
       this.valor=valor;
        initComponents();
        //descomentar esto 
        //new bloquear( this ).block();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLnumeror = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jccarreras = new javax.swing.JComboBox<>();
        jLcarrdepto = new javax.swing.JLabel();
        jtnum = new javax.swing.JTextField();
        jtcorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtnombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jbiniciarsesion = new javax.swing.JButton();
        jCdeptos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLnumeror.setFont(new java.awt.Font("Ubuntu Mono", 1, 20)); // NOI18N
        jLnumeror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLnumeror.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLnumeror, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 450, 20));

        jLabel4.setFont(new java.awt.Font("Ubuntu Mono", 1, 20)); // NOI18N
        jLabel4.setText("Nombre completo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        jccarreras.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jccarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería en Eléctrica", "Ingeniería en Comunicaciones y Electrónica", "Ingeniería en Control y Automatización", "Ingeniería Fotónica", "Ingeniería en Sistemas Automotrices" }));
        jPanel1.add(jccarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        jLcarrdepto.setFont(new java.awt.Font("Ubuntu Mono", 1, 20)); // NOI18N
        jLcarrdepto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLcarrdepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 450, 20));

        jtnum.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jtnum.setMinimumSize(new java.awt.Dimension(65, 25));
        jtnum.setPreferredSize(new java.awt.Dimension(65, 25));
        jtnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnumActionPerformed(evt);
            }
        });
        jPanel1.add(jtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 450, -1));

        jtcorreo.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jtcorreo.setPreferredSize(new java.awt.Dimension(65, 25));
        jPanel1.add(jtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 450, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu Mono", 1, 20)); // NOI18N
        jLabel6.setText("Correo Institucional");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, -1, -1));

        jtnombre.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jtnombre.setPreferredSize(new java.awt.Dimension(65, 25));
        jPanel1.add(jtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 450, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255, 1));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        jbiniciarsesion.setBackground(new java.awt.Color(0, 0, 0));
        jbiniciarsesion.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jbiniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        jbiniciarsesion.setText("OK");
        jbiniciarsesion.setBorder(null);
        jbiniciarsesion.setBorderPainted(false);
        jbiniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbiniciarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(jbiniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 70, -1));

        jCdeptos.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jCdeptos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coordinación de Enlace y Gestión Técnica", "Departamento de Capital Humano", "Departamento de Evaluación y Seguimiento Académico", "Departamento de Extensióm y Apoyos Educativos", "Departamento de Formación Científica Básica", "Departamento de Gestión Escolar", "Departamento de Ingeniería Eléctrica", "Departamento de Ingeniería en Comunicaciones y Eléctronica", "Departamento de Ingeniería en Control y Automatización", "Departamento de Ingeniería en Sistemas Automotrices", "Departamento de Ingeniería Fotónica", "Departamento de Innovación Educativa", "Departamento de Investigación", "Departamento de Mantenimiento y Servicios", "Departamento de Posgrado", "Departamento de Recursos Financieros", "Departamento de Recursos Materiales", "Departamento de Servicios Estudiantiles", "Dirección", "Sección de Estudios de Posgrado e Investigación", "Subdirección Académica", "Subdirección Administrativa", "Subdirección de Servicios Educativos e Integración Social", "Unidad de Tenología Educativa y Campus Virtual", "Unidad Politécnica de Integración Social" }));
        jPanel1.add(jCdeptos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 440, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255, 220));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 760, 480));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //regresa a la pantalla de login 
        new Principal().setVisible(true);       
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbiniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbiniciarsesionActionPerformed
      
        //inicia sesión
        String url = "http://148.204.37.66/serverRegistroLabs/signin.php";
        String charset = "UTF-8";
        // Datos a enviar en la solicitud POST
        String idUsuario = jtnum.getText();
            String nombre = jtnombre.getText();
            String correo = jtcorreo.getText();
            int idTipot= valor+1;
            int idDeptoCarrerat;
            if(valor==3)
                idDeptoCarrerat=jCdeptos.getSelectedIndex()+1;
            else
                idDeptoCarrerat=jccarreras.getSelectedIndex()+1;
        
            String idTipo = String.valueOf(idTipot);
        String idDeptoCarrera= String.valueOf(idDeptoCarrerat);
        try {
            // Codificar los parámetros
            String parametros = "idUsuario=" + URLEncoder.encode(idUsuario, charset)
                    + "&nombre=" + URLEncoder.encode(nombre, charset)
                    + "&correo=" + URLEncoder.encode(correo, charset)
                    + "&idTipo=" + URLEncoder.encode( idTipo, charset)
                    + "&idDeptoCarrera=" + URLEncoder.encode(idDeptoCarrera, charset);
            
            // Crear la conexión HTTP POST
            URL urlObj = new URL(url);
            HttpURLConnection conn = (HttpURLConnection) urlObj.openConnection();
            conn.setRequestMethod("POST");
            conn.setDoOutput(true);
            
            // Enviar los parámetros en el cuerpo de la solicitud
            try (DataOutputStream wr = new DataOutputStream(conn.getOutputStream())) {
                wr.writeBytes(parametros);
                wr.flush();
            }
            
            // Obtener la respuesta del servidor
            BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            String linea;
            StringBuilder respuesta = new StringBuilder();
            while ((linea = in.readLine()) != null) {
                respuesta.append(linea);
            }
            in.close();
            conn.disconnect();
            
            // Procesar la respuesta
            String jsonRespuesta = respuesta.toString();
            if (jsonRespuesta.contains("\"res\":true")) {
                
                 new Docente(valor).setVisible(true);
                 this.dispose();
            }else{
                new Principal().setVisible(true);
                 this.dispose();
            }
                
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jbiniciarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox<String> jCdeptos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLcarrdepto;
    public javax.swing.JLabel jLnumeror;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbiniciarsesion;
    public javax.swing.JComboBox<String> jccarreras;
    private javax.swing.JTextField jtcorreo;
    private javax.swing.JTextField jtnombre;
    private javax.swing.JTextField jtnum;
    // End of variables declaration//GEN-END:variables
}
